events {
    worker_connections 1024;
}

http {
    upstream api {
        server api:3000;
    }

    upstream customer {
        server customer:3000;
    }

    upstream rider {
        server rider:3000;
    }

    upstream store {
        server store:3000;
    }

    upstream admin {
        server admin:3000;
    }

    server {
        listen 80;
        server_name quickdelivery.homes www.quickdelivery.homes;

        location / {
            proxy_pass http://customer;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name admin.quickdelivery.homes;

        location / {
            proxy_pass http://admin;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name rider.quickdelivery.homes;

        location / {
            proxy_pass http://rider;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    server {
        listen 80;
        server_name store.quickdelivery.homes;

        location / {
            proxy_pass http://store;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            proxy_pass http://api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}